apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    app: {{ .Chart.Name }}-app
    chart: {{ .Chart.Name }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}-app